# DOCS: write about waiting and race conditions with -d 
# DOCS: write about firebase emulator


services:
  database:
    image: mysql:8.0
    tmpfs:
      - /var/lib/mysql
    ports: 
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_DATABASE: "url_shortener"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -P 3306 -uroot -p\"$${MYSQL_ROOT_PASSWORD}\" --silent"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 30s
  db-migration:
      build:
         context: ./backend
         dockerfile: Dockerfile
      image: db-migration:test
      depends_on:
        database:
          condition: service_healthy
  firebase-emulator:
    image: evolutecx/firebase-emulator:latest
    ports:
      - 14000:4000 #Emulator UI
      - 19099:9099 #Firebase Auth
    environment:
      - FB_PROJECT_ID=url-shortener-abadb
  nginx:
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      redis:
        condition: service_started
      database:
        condition: service_started
      firebase-emulator:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost/nginx-health"]
      
