services:
  database:
    image: mysql:8.0
    tmpfs:
      - /var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_DATABASE: "url_shortener"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -P 3306 -uroot -p\"$${MYSQL_ROOT_PASSWORD}\" --silent"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 30s
  db-migration:
      build:
         context: ../backend
         dockerfile: Dockerfile
      image: db-migration:test
      depends_on:
        database:
          condition: service_healthy
  # firebase-emulator:
  #   image: evolutecx/firebase-emulator:latest
  #   ports:
  #     - 14000:4000 #Emulator UI
  #     - 19099:9099 #Firebase Auth
  #   environment:
  #     - FB_PROJECT_ID=url-shortener-abadb
  nginx:
    volumes:
      - ./reverse-proxy-config/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      redis:
        condition: service_started
      database:
        condition: service_started
      #firebase-emulator:
      # condition: service_started
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost/nginx-health"]

  backend:
      build:
        context: ../backend
        dockerfile: Dockerfile
      image: backend:dev
      ports:
        - "8000:8000"
      volumes:
        - ../backend/src:/app/src
      command: ["sh", "-c", "uvicorn src.url_shortener.main:app --reload --host 0.0.0.0 --port 8000"]
      depends_on:
        db-migration:
          condition: service_completed_successfully
        redis:
          condition: service_healthy
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/dependencies"]
        interval: 30s
        timeout: 5s
        retries: 5
        start_period: 5s
      env_file:
      - ${BACKEND_ENV_FILE}
